apiVersion: 1

datasources:
  - name: ClickHouse Analytics
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse-analytics
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: ${CLICKHOUSE_DB}
      username: ${CLICKHOUSE_USER}
      tlsSkipVerify: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
